AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to provision storage solution for project space.
Parameters:
  StorageSize:
    Description: Size of the storage in gb
    Default: 5
    Type: Number
  VolumeType:
    Description: EBS Volume type
    Default: gp2
    Type: String
    AllowedValues: [gp2, io1, st1, sc1]
  Iops:
    Description: The number of I/O operations per second (IOPS), required when the volume type is io1
    Default: 0
    Type: Number
  SnapshotId:
    Description: SnapshotId if available
    Default: ""
    Type: String
Conditions:

  HasIops: !Not [ !Equals [ !Ref Iops, 0 ] ]

Resources:
  DataStoreVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-southeast-2a
      Encrypted: true
      Iops:
        Fn::If: # Needs long-form version or stackup throws an error...
          - HasIops
          - Ref: Iops
          - Ref: AWS::NoValue
      Size: !Ref StorageSize
      SnapshotId: !Ref SnapshotId
      Tags:
        - Key: Name
          Value: 'volume-from-template1.yaml-delete-me'
      VolumeType: !Ref VolumeType
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
